
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: authentication_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '127.0.0.1:5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    image: auth-service:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/authentication_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    ports:
      - '8082:8083'
    restart: unless-stopped

volumes:
  postgres-data:
